// AUTO-GENERATED from "Final Seating Data.xlsx" (Office = AIWC).
// Columns: [seatNumber, employeeCode, name, department, seatingCategory, category]
export type RawRow = [string, string, string, string, string, string]
export const AIWC_ROWS: RawRow[] = [
  ["1", "1409HO", "Rajiv Ranjan", "HR Operations", "Workstation", "Employee"],
  ["2", "6689HO", "Khushboo Vishwakarma", "HR Operations", "Workstation", "Employee"],
  ["3", "3887HO", "Surender Singh", "HR Operations", "Workstation", "Employee"],
  ["4", "5758HO", "Sushil Kumar Bhatt", "HR Operations", "Workstation", "Employee"],
  ["5", "8922HO", "Srishti Arora", "HR Operations", "Workstation", "Employee"],
  ["6", "N/A", "Sahil Rastogi", "HR Operations", "Workstation", "Employee"],
  ["7", "11019HO", "Ayushi", "HR Operations", "Workstation", "Employee"],
  ["8", "11018HO", "Ayushma Arpita", "HR Operations", "Workstation", "Employee"],
  ["9", "9442HO", "Ankit Jakhar", "POWER", "Workstation", "Employee"],
  ["10", "8978HO", "Ashish Mehta", "POWER", "Workstation", "Employee"],
  ["11", "9430HO", "Prajjwal Tiwari", "POWER", "Workstation", "Employee"],
  ["12", "9597HO", "Ramvilas Yadav", "POWER", "Workstation", "Employee"],
  ["13", "Vacant", "Vacant", "N/A", "Workstation", "Vacant"],
  ["14", "N/A", "Ankit kumar", "POWER", "Workstation", "Employee"],
  ["15", "7008HO", "Bhupander", "POWER", "Workstation", "Employee"],
  ["16", "10264HO", "Sakshi", "POWER", "Workstation", "Employee"],
  ["17", "10540HO", "Princy Chauhan", "POWER", "Workstation", "Employee"],
  ["18", "10095HO", "Vanshika Chuhan", "POWER", "Workstation", "Employee"],
  ["19", "2451HO", "Pardeep kumar", "FINANCE", "Workstation", "Employee"],
  ["20", "6782HO", "Boby", "FINANCE", "Workstation", "Employee"],
  ["21", "7023HO", "Jitendra Singla", "FINANCE", "Workstation", "Employee"],
  ["22", "3292BR", "Priyanka Mittal", "FINANCE", "Workstation", "Employee"],
  ["23", "9090HO", "Divya Vohra", "FINANCE", "Workstation", "Employee"],
  ["24", "8357HO", "Sukhvinder Singh Daid", "FINANCE", "Workstation", "Employee"],
  ["25", "8278HO", "Sanjay Gupta", "FINANCE", "Workstation", "Employee"],
  ["26", "6653HO", "Aryan Sharma", "FINANCE", "Workstation", "Employee"],
  ["27", "5941HO", "Vipin Kumar V", "FINANCE", "Workstation", "Employee"],
  ["28", "3326HO", "Narender Singh", "FINANCE", "Workstation", "Employee"],
  ["29", "6054HO", "Basant Mishra", "FINANCE", "Workstation", "Employee"],
  ["30", "1563BR", "Ritesh Kumar", "COMPLIANCE CELL", "Workstation", "Employee"],
  ["31", "2227HO", "Pawan kumar", "COMPLIANCE CELL", "Workstation", "Employee"],
  ["32", "10594HO", "Aryan Kaushik", "COMPLIANCE CELL", "Workstation", "Employee"],
  ["33", "2592HO", "Rahul Mishra", "FINANCE", "Workstation", "Employee"],
  ["34", "6310HO", "Deepak Yadav", "FINANCE", "Workstation", "Employee"],
  ["35", "11017HO", "Deepanshu", "FINANCE", "Workstation", "Employee"],
  ["36", "Intern", "Aarnav Raj", "TECH INNOVATION", "Workstation", "Intern"],
  ["37", "Silver Touch", "Shivangi", "TECH INNOVATION", "Workstation", "Silver Touch"],
  ["38", "11307HO", "Kesar Sharma", "TECH INNOVATION", "Workstation", "Employee"],
  ["39", "10431HO", "Anantika Bisht", "TECH INNOVATION", "Workstation", "Employee"],
  ["40", "Silver Touch", "Vinit Mishra", "TECH INNOVATION", "Workstation", "Silver Touch"],
  ["41", "10712HO", "Anoop Kumar Srivasatava", "TECH INNOVATION", "Workstation", "Employee"],
  ["42", "Silver Touch", "Sachin Dagar", "TECH INNOVATION", "Workstation", "Silver Touch"],
  ["43", "Vacant", "Vacant", "N/A", "Workstation", "Vacant"],
  ["44", "9491HO", "Yogesh Rathore", "IT DEPARTMENT", "Workstation", "Employee"],
  ["45", "9274HO", "Balveer Singh", "IT DEPARTMENT", "Workstation", "Employee"],
  ["46", "Vacant", "Vacant", "N/A", "Workstation", "Vacant"],
  ["47", "11253HO", "Nishu Kumari", "Talent Management", "Workstation", "Employee"],
  ["48", "8170HO", "Garima Vijay", "Talent Management", "Workstation", "Employee"],
  ["49", "10016HO", "Shreya Gupta", "Talent Management", "Workstation", "Employee"],
  ["50", "9982HO", "Kirti Setia", "Talent Management", "Workstation", "Employee"],
  ["51", "Vacant", "Vacant", "N/A", "Workstation", "Vacant"],
  ["52", "10726HO", "Neha Ashish Jain", "Talent Management", "Workstation", "Employee"],
  ["53", "Vacant", "Vacant", "N/A", "Workstation", "Vacant"],
  ["54", "8381HO", "Harshit Kumar", "TECH INNOVATION", "Workstation", "Employee"],
  ["55", "6802HO", "Preeti Bansala", "Talent Acquisition", "Workstation", "Employee"],
  ["56", "11262HO", "Anjali Priyadarshini", "Talent Acquisition", "Workstation", "Employee"],
  ["57", "11272HO", "Divyansh Kumar", "Talent Acquisition", "Workstation", "Employee"],
  ["58", "10494HO", "Prashant Chaudhary", "WATER AND URBAN", "Workstation", "Employee"],
  ["59", "8169HO", "Sanya bansal", "WATER AND URBAN", "Workstation", "Employee"],
  ["60", "4665HO", "Aiman Shakeel", "WATER AND URBAN", "Workstation", "Employee"],
  ["61", "9694HO", "Virendra Kumar", "WATER AND URBAN", "Workstation", "Employee"],
  ["62", "10173HO", "Monisha Jain", "WATER AND URBAN", "Workstation", "Employee"],
  ["63", "10668HO", "Lokesh Singh Thakur", "WATER AND URBAN", "Workstation", "Employee"],
  ["64", "6999HO", "Ravinder Kumar", "WATER AND URBAN", "Workstation", "Employee"],
  ["65", "9980HO", "Siddharth Sharma", "WATER AND URBAN", "Workstation", "Employee"],
  ["66", "8239HO", "Shivam Raj Singh", "WATER AND URBAN", "Workstation", "Employee"],
  ["67", "11386HO", "Manoj Kumar Das", "Urban, Water & Hydropower", "Workstation", "Employee"],
  ["68", "11255HO", "Yashraj Singh Dharmeshkumar Dodia", "WATER AND URBAN", "Workstation", "Employee"],
  ["69", "N/A", "Kaushal Jha", "Tech-Innovation", "Workstation", "Silver Touch"],
  ["70", "10663HO", "Vikram Singh", "CMD OFFICE", "Workstation", "Employee"],
  ["71", "11413HO", "Rakesh Kumar", "CMD OFFICE", "Workstation", "Employee"],
  ["72", "10481HO", "Parkhar Prakash", "TECH INNOVATION", "Workstation", "Employee"],
  ["73", "10512HO", "Chetan", "ADMIN", "Workstation", "Employee"],
  ["74", "11072HO", "Mondeep Singh", "ADMIN", "Workstation", "Employee"],
  ["75", "10266HO", "Ram Ratan", "ADMIN", "Workstation", "Employee"],
  ["76", "3711HO", "Sagar", "ADMIN", "Workstation", "Employee"],
  ["77", "N/A", "Lalit Sharma", "ADMIN", "Workstation", "Employee"],
  ["78", "5759HO", "Jitendra Kumar Yadav", "ADMIN", "Workstation", "Employee"],
  ["79", "N/A", "Sudhir kumar", "IT DEPARTMENT", "Workstation", "Employee"],
  ["80", "11016HO", "Sai Priya Narkurthy", "CMD OFFICE", "Workstation", "Employee"],
  ["81", "9802HO", "Mahesh Joshi", "COS Cell", "Workstation", "Employee"],
  ["82", "10452HO", "Maaz Shahid", "TECH INNOVATION", "Workstation", "Employee"],
  ["83", "9006HO", "Piyush Agnihotri", "TECH INNOVATION", "Workstation", "Employee"],
  ["84", "Silver Touch", "Gokul Bhatt", "TECH INNOVATION", "Workstation", "Employee"],
  ["85", "Silver Touch", "Arnav Nath", "TECH INNOVATION", "Workstation", "Employee"],
  ["86", "10338HO", "Umesh Verma", "TECH INNOVATION", "Workstation", "Employee"],
  ["87", "6015HO", "Vineet Kumar Sachan", "TECH INNOVATION", "Workstation", "Employee"],
  ["88", "11285HO", "Ankit Jangid", "TECH INNOVATION", "Workstation", "Employee"],
  ["89", "Silver Touch", "Sachin Bansal/Archna", "TECH INNOVATION", "Workstation", "Silver Touch"],
  ["90", "10645HO", "Aashima Banga", "TECH INNOVATION", "Workstation", "Employee"],
  ["91", "11015HO", "T.S. Praveen Kumar", "CMD OFFICE", "Workstation", "Employee"],
  ["92", "9842HO", "Amrit  Kumar singh/Raman Kumar", "TECH INNOVATION", "Workstation", "Employee"],
  ["93", "Silver Touch", "Pintu Kumar Chaurasia", "TECH INNOVATION", "Workstation", "Silver Touch"],
  ["94", "11384HO", "Chanchal Kumar", "TECH INNOVATION", "Workstation", "Employee"],
  ["95", "10347HO", "Aakirti Rai", "TECH INNOVATION", "Workstation", "Employee"],
  ["96", "9202HO", "Syed Nabeel Hussain", "TECH INNOVATION", "Workstation", "Employee"],
  ["97", "9201BR", "Prernika", "TECH INNOVATION", "Workstation", "Employee"],
  ["98", "10486HO", "Ravi Shankar", "IT DEPARTMENT", "Workstation", "Employee"],
  ["99", "93671HO", "Md.  Shafiullah Qurashi", "TECH INNOVATION", "Workstation", "Employee"],
  ["100", "9391HO", "Aryan Giri", "TECH INNOVATION", "Workstation", "Employee"],
  ["101", "5862HO", "Ajit Kumar", "TECH INNOVATION", "Workstation", "Employee"],
  ["102", "6235MH", "Nishant Sagar", "TECH INNOVATION", "Workstation", "Employee"],
  ["103", "10539HO", "Rishish Kumar Jha", "TECH INNOVATION", "Workstation", "Employee"],
  ["104", "10390HO", "Naresh Kumar", "TECH INNOVATION", "Workstation", "Employee"],
  ["105", "8571HO", "Pratima Pathak", "COO", "Workstation", "Employee"],
  ["106", "9776HO", "Anusha Mishra", "TECH INNOVATION", "Workstation", "Employee"],
  ["107", "10662HO", "Avneesh Pandey", "TECH INNOVATION", "Workstation", "Employee"],
  ["108", "10616HO", "Ravi Prakash", "TECH INNOVATION", "Workstation", "Employee"],
  ["109", "10583HO", "Saransh Kumar", "TECH INNOVATION", "Workstation", "Employee"],
  ["110", "10371HO", "Manoj Kumar", "TECH INNOVATION", "Workstation", "Employee"],
  ["111", "Silver Touch", "Khushwinder", "TECH INNOVATION", "Workstation", "Silver Touch"],
  ["112", "10525HO", "Kunal Green", "TECH INNOVATION", "Workstation", "Employee"],
  ["113", "11265HO", "Akshay Rajesh Kalje", "TECH INNOVATION", "Workstation", "Employee"],
  ["114", "11020HO", "Ali Amjad", "TECH INNOVATION", "Workstation", "Employee"],
  ["115", "11267HO", "Devika Badekar", "TECH INNOVATION", "Workstation", "Employee"],
  ["116", "11248HO", "Sampada  Sudhir Mahulkar", "BD DEPARTMENT", "Workstation", "Employee"],
  ["117", "9892HO", "Satyam", "BD DEPARTMENT", "Workstation", "Employee"],
  ["118", "N/A", "Anushree Srivastava", "TECH INNOVATION", "Workstation", "Employee"],
  ["119", "Vacant", "Vacant", "Vacant", "Workstation", "Vacant"],
  ["120", "11251HO", "Vaibhav Singh Negi", "BD DEPARTMENT", "Workstation", "Employee"],
  ["121", "6748HO", "Nipun Anand", "BD DEPARTMENT", "Workstation", "Employee"],
  ["122", "1016HO", "Khoni Lal Sharma", "BD DEPARTMENT", "Workstation", "Employee"],
  ["123", "10176HO", "Shuryanshu Prakash", "BD DEPARTMENT", "Workstation", "Employee"],
  ["124", "10183HO", "Angki", "BD DEPARTMENT", "Workstation", "Employee"],
  ["125", "11273HO", "Karunya", "TECH INNOVATION", "Workstation", "Employee"],
  ["126", "11227HO", "Anurag Rai", "TECH INNOVATION", "Workstation", "Employee"],
  ["127", "N/A", "Alan R Thomas", "TECH INNOVATION", "Workstation", "Employee"],
  ["128", "11264HO", "Mohd Amaan", "TECH INNOVATION", "Workstation", "Employee"],
  ["129", "11274HO", "Aditya Chinta", "TECH INNOVATION", "Workstation", "Employee"],
  ["130", "11023HO", "Puneet Upadhyay", "TECH INNOVATION", "Workstation", "Employee"],
  ["131", "11022HO", "Harshil Nandaniya", "TECH INNOVATION", "Workstation", "Employee"],
  ["132", "11021HO", "Gaurav Jain", "TECH INNOVATION", "Workstation", "Employee"],
  ["133", "11263HO", "Soumav  Mitra", "TECH INNOVATION", "Workstation", "Employee"],
  ["134", "11284HO", "Anurag Rathore", "TECH INNOVATION", "Workstation", "Employee"],
  ["135", "Not generated", "Anmol Soni", "TECH INNOVATION", "Workstation", "Employee"],
  ["136", "11269HO", "Aryan Narang/Harshil Undhad", "Branding and Communication", "Workstation", "Employee"],
  ["137", "10300HO", "Astha", "Branding and Communication", "Workstation", "Employee"],
  ["138", "10082HO", "Vijay", "Branding and Communication", "Workstation", "Employee"],
  ["139", "9944HO", "Shivam Vikram Singh", "Branding and Communication", "Workstation", "Employee"],
  ["140", "9880HO", "Minal kushwaha", "Branding and Communication", "Workstation", "Employee"],
  ["141", "9450HO", "Vibhuti Kanodia", "Branding and Communication", "Workstation", "Employee"],
  ["142", "9886HO", "Tanuska Chatterjee", "Branding and Communication", "Workstation", "Employee"],
  ["143", "11270HO", "Raghav Mendiratta", "Branding and Communication", "Workstation", "Employee"],
  ["144", "Not generated", "Pawan Rajput", "TECH INNOVATION", "Workstation", "Employee"],
  ["CMD Cell", "2051HO", "Neeraj Narnolia", "CMD OFFICE", "Cabin Cell Cabin", "Employee"],
  ["CMD Cell", "Vacant", "Vacant", "CMD OFFICE", "Cabin Cell Cabin", "Vacant"],
  ["CMD Cell", "11030HO", "Vishaka Sinha", "CMD OFFICE", "Cabin", "Employee"],
  ["COS Cell", "9742HO", "Deepshikha Lather", "COS Cell", "COS Cell Cabin", "Employee"],
  ["COS Cell", "9741HO", "Surabhi Pandey", "COS Cell", "COS Cell Cabin", "Employee"],
  ["COS Cell", "9946HO", "Jai Vardhan Sharma", "COS Cell", "COS Cell Cabin", "Employee"],
  ["COS Cell", "Intern", "Pavithra Kumaraguru", "COS Cell", "COS Cell Cabin", "Intern"],
  ["COS Cell", "Intern", "Anish Raj", "COS Cell", "COS Cell Cabin", "Intern"],
  ["LHS-1", "Vacant", "Vacant", "Vacant", "Cabin", "Vacant"],
  ["LHS-2", "1726HO", "Sapan Gupta", "FINANCE", "Cabin", "Employee"],
  ["LHS-3", "2539HO", "Chitranjan Singh", "COMPLIANCE CELL", "Cabin", "Employee"],
  ["LHS-4", "Vacant", "Vacant", "Vacant", "Cabin", "Vacant"],
  ["Manthan", "6531HO", "Aayush Raj", "COS Cell", "Cabin", "Employee"],
  ["RHS-1", "1001HO", "Raj Kumar", "CMD OFFICE", "Cabin", "Employee"],
  ["RHS-2", "1013HO", "Anshuman Krishanu", "COO", "Cabin", "Employee"],
  ["RHS-3", "10345HO", "N N Sinha", "TECH INNOVATION", "Cabin", "Employee"],
  ["RHS-4", "N/A", "Usha Singh", "CMD OFFICE", "Cabin", "Employee"],
  ["RHS-5", "9189HO", "Kanhaaya Dayal Singh", "WATER AND URBAN", "Cabin", "Employee"],
  ["VR Room", "Silver Touch", "Kaushal Jha", "TECH INNOVATION", "VR Room", "Silver Touch"],
  ["VR Room", "Intern", "Pradeep Singh", "TECH INNOVATION", "VR Room", "Intern"],
  ["Workstation", "Intern", "Priya Priyadarshini", "TECH INNOVATION", "Overhead", "Intern"],
  ["Workstation", "Intern", "Ashmit Sharma", "TECH INNOVATION", "Overhead", "Intern"],
  ["Workstation", "Intern", "Soundharam", "Branding and Communication", "Overhead", "Intern"],
]
